### ISSUE TITLE
Possible to setup metaocaml with utop?

### ISSUE THREAD

**Issue by abhi18av** [yallop/metaocaml-letrec#5]
Hi @yallop 

I was wondering if it's somehow possible to have the same kind of `utop` support of `metaocaml` as well.

I use the `ocaml` layer in `spacemacs` and since by default `utop emacs mode` is not working for `spacemacs`, I'm exploring the`ocaml` toplevel - which seems an absolute minimum repl to be sure. 

Is there a way, I could have a more interactive experience with `metaocaml` ?

**Comment by yallop** [comment]
It may be possible.  You'd need to arrange for the right object files to be loaded, and then call 

```
#install_printer Codelib.print_code
#install_printer Codelib.print_closed_code
```

The code that builds and initializes the top level is in the `ber-metaocaml` repository.  Here are the build rules for the `metaocaml` top level that show which object files `.cmo` and `.cma` are involved:
https://github.com/metaocaml/ber-metaocaml/blob/7fccae53/ber-metaocaml-107/Makefile#L60-L68

And here's the top-level hook that installs the printers:
https://github.com/metaocaml/ber-metaocaml/blob/7fccae53/ber-metaocaml-107/bertop.ml

**Comment by abhi18av** [comment]
Whoops, forgot to reply to thi sone!

Actually, I tried this at the time but couldn't make it work. Apologies for the late response @yallop 😓

**Comment by yallop** [comment]
@abhi8av: if you're still hoping to get this working, could you provide more detail about what didn't work, and how?  (If you're no longer looking to set up MetaOCaml with utop, let's close this issue.)

**Comment by abhi18av** [comment]
Oh, actually I am quite sure to be coming around to this in a couple months but as of now I'm occupied. So, I'll close this and report updates once I have some :)
